# Generated by Django 5.2.7 on 2025-11-11 15:08

import django.db.models.deletion
import django_countries.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255)),
                ('project_description', models.TextField()),
                ('cover_image', models.ImageField(upload_to='cover_images/')),
                ('project_location', django_countries.fields.CountryField(max_length=2)),
                ('project_field', models.CharField(choices=[('TECH', 'Technology'), ('AGRI', 'Agriculture'), ('FASH', 'Fashion'), ('HEALTH', 'Health'), ('EDU', 'Education'), ('FIN', 'Finance')], max_length=50)),
                ('project_products', models.ImageField(blank=True, null=True, upload_to='project_products/')),
                ('project_document', models.FileField(blank=True, null=True, upload_to='project_documents/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
